src/objects/IoT_Debug_Log__c.object
<CustomObject>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>IoT Debug Log</label>
    <nameField>
        <label>IoT Debug Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IoT Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Slack_Message__c.object
<CustomObject>
    <description>A message object to be used with Slack Webhooks.</description>
    <fields>
        <fullName>Text__c</fullName>
        <label>Text</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Slack Message</label>
    <nameField>
        <label>Slack Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Slack Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Slack_PE_Settings__c.object
<CustomObject>
    <description>A config object to use for Slack integration. It supplies the webhook URL.</description>
    <fields>
        <fullName>webhook__c</fullName>
        <description>URL for incoming webhooks to your Slack application.</description>
        <label>webhook</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Slack PE Settings</label>
    <nameField>
        <label>Slack Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Slack PE Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SlackPublisher.cls
public class SlackPublisher {
    
    @InvocableMethod(label='Post to Slack')
    public static void postToSlack(List<Slack_Message__c> messages) {

        String slackURL; 
        
        Slack_PE_Settings__c[] config = [SELECT webhook__c FROM Slack_PE_Settings__c WHERE Name = 'iot-explorer'];
       
        if (config.size() > 0) {
            System.debug('webhhook = ' + config[0].webhook__c);
            slackURL = config[0].webhook__c;
        }
        
        for (Slack_Message__c message:messages) {
        
            Map<String,Object> msg = new Map<String,Object>();
        
            msg.put('text', message.Text__c);
            msg.put('mrkdwn', true);
        
            String body = JSON.serialize(msg);    
            System.enqueueJob(new QueueableSlackCall(slackURL, 'POST', body));
        }
    }
     
    public class QueueableSlackCall implements System.Queueable, Database.AllowsCallouts {
         
        private final String url;
        private final String method;
        private final String body;
   
        private IoT_Debug_Log__c debugLog; 
        
        public QueueableSlackCall(String url, String method, String body) {
            this.url = url;
            this.method = method;
            this.body = body;
            this.debugLog = new IoT_Debug_Log__c();
        }
         
        public void execute(System.QueueableContext ctx) {
            
            HttpRequest req = new HttpRequest();
            req.setEndpoint(url);
            req.setMethod(method);
            req.setBody(body);
            Http http = new Http();
            HttpResponse res = http.send(req);
            
            // create a new LOG output object for every request/response pair
            debugLog.Name = req.getBody();
            debugLog.Message__c = res.getBody();
        }
        
    }
   
}